[package]
name = "lite-markdown"
version = "0.1.0"
description = "ものすごく軽量な Markdown エディタ"
authors = ["you"]
edition = "2021"

[lib]
name = "lite_markdown_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

[profile.release]
# バイナリを可能な限り小さく・軽量に。
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
